// <auto-generated />
using System;
using MagicstoreAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagicstoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250324230038_TablesFirstBuild")]
    partial class TablesFirstBuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.Beers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("estilo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("cervezas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            estilo = "IPA",
                            nombre = "IPA Classic",
                            pais = "USA"
                        },
                        new
                        {
                            id = 2,
                            estilo = "Ale",
                            nombre = "Golden Ale",
                            pais = "UK"
                        },
                        new
                        {
                            id = 3,
                            estilo = "Stout",
                            nombre = "Stout Premium",
                            pais = "Ireland"
                        },
                        new
                        {
                            id = 4,
                            estilo = "Lager",
                            nombre = "Amber Lager",
                            pais = "Germany"
                        });
                });

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.Permissions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MSDB_Permissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "All access",
                            Permission = "Permiso1"
                        },
                        new
                        {
                            ID = 2,
                            Description = "descripcionpermiso",
                            Permission = "perm 2"
                        },
                        new
                        {
                            ID = 3,
                            Description = "tres",
                            Permission = "perm 3"
                        },
                        new
                        {
                            ID = 4,
                            Description = "just view",
                            Permission = "perm4"
                        },
                        new
                        {
                            ID = 5,
                            Description = "mantenimiento",
                            Permission = "perm 5"
                        });
                });

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.RolePermissions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MSDB_RolesPermissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = false,
                            Permission = "Permiso 1",
                            PermissionID = 1,
                            Role = "Super Admin",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 2,
                            Active = false,
                            Permission = "Permiso 2",
                            PermissionID = 2,
                            Role = "Super Admin",
                            RoleID = 1
                        },
                        new
                        {
                            ID = 3,
                            Active = false,
                            Permission = "Permiso 3",
                            PermissionID = 3,
                            Role = "User ",
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MSDB_Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Role = "Super Admin"
                        },
                        new
                        {
                            ID = 2,
                            Role = "User"
                        },
                        new
                        {
                            ID = 3,
                            Role = "Viewer"
                        },
                        new
                        {
                            ID = 4,
                            Role = "Administrator"
                        },
                        new
                        {
                            ID = 5,
                            Role = "Developer"
                        });
                });

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.UserRoles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("MSDB_UserRoles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            Role = "Super Admin",
                            RoleID = 1,
                            User = "user",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            Role = "User",
                            RoleID = 2,
                            User = "user2",
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            Role = "Viewer",
                            RoleID = 3,
                            User = "user2",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("MagicstoreAPI.Infrastructures.Entities.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MSDB_Users");

                    b.HasData(
                        new
                        {
                            ID = 5,
                            CreationDate = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mail = "user4@example.com",
                            PasswordHash = new byte[] { 92, 51, 48, 55, 79, 92, 50, 55, 53, 92, 50, 50, 48, 118, 92, 51, 55, 49, 88, 62, 107, 92, 92, 48, 87, 92, 51, 48, 52, 92, 51, 52, 52, 92, 48, 48, 51, 81, 92, 50, 51, 51, 67, 92, 50, 49, 54, 92, 50, 52, 48, 92, 51, 52, 52, 92, 51, 53, 53, 92, 50, 53, 49, 118, 89, 92, 50, 49, 54, 117, 104, 92, 51, 50, 52, 92, 50, 51, 52, 92, 50, 54, 49, 92, 51, 55, 51, 92, 50, 53, 55, 94, 92, 51, 53, 50, 92, 50, 51, 53, 92, 51, 53, 50, 92, 50, 49, 50, 122, 92, 50, 49, 51, 92, 51, 48, 55, 39, 92, 51, 49, 48, 92, 48, 48, 48, 92, 50, 54, 48, 61, 92, 51, 55, 53, 68, 92, 50, 48, 53, 68, 92, 48, 51, 54, 126, 92, 50, 49, 48, 92, 48, 49, 56, 83, 57, 68, 92, 51, 51, 53 },
                            PasswordSalt = new byte[] { 39, 70, 92, 51, 49, 51, 92, 51, 54, 52, 92, 51, 54, 48, 92, 50, 49, 49, 92, 51, 51, 55, 80, 92, 51, 52, 54, 64, 92, 51, 53, 53, 92, 48, 48, 48, 92, 51, 52, 52, 74, 92, 50, 49, 48, 92, 48, 48, 55, 44, 92, 51, 50, 54, 92, 51, 54, 55, 92, 48, 48, 52, 92, 50, 54, 50, 59, 92, 51, 55, 48, 92, 50, 54, 50, 92, 48, 48, 50, 92, 50, 51, 53, 92, 48, 49, 51, 92, 50, 52, 49, 87, 92, 50, 54, 55, 77, 82, 92, 50, 50, 53, 88, 68, 92, 51, 54, 54, 121, 92, 50, 48, 49, 92, 50, 51, 49, 92, 50, 48, 51, 92, 51, 54, 52, 92, 51, 48, 49, 92, 48, 49, 57, 42, 42, 92, 48, 49, 56, 120, 92, 50, 49, 50, 114, 61, 92, 50, 51, 50, 114, 72, 92, 51, 48, 55 },
                            UserName = "user5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
