
trigger:
- main

pool:
  name: Default 

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MagicstoreAPI/MagicstoreAPI/MagicstoreAPI.csproj'
    workingDirectory: '$(Build.SourcesDirectory)/MagicstoreAPI/MagicstoreAPI'

